[[snippets]]
  description = "no description"
  command = "check"
  output = ""

[[snippets]]
  description = "list all"
  command = "ls"
  tag = ["ls"]
  output = ""

[[snippets]]
  description = "just check"
  command = "ls"
  output = ""

[[snippets]]
  description = "docker container list - coloumn view"
  command = "docker container ls --format='table {{.ID}} \t {{.Names}} \t {{.Image}} \t {{.Status}} \t {{.Ports}}'"
  output = ""

[[snippets]]
  description = "generate ssh key"
  command = "ssh-keygen -t ed25519 -C \"<email=hariprasadcsmails@gmail.com>\""
  output = ""
